server: 
  port: 9010
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.29.53:3306/tensquare_qa?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itcat
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6867/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

