#指定服务的端口
server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.29.53:3306/tensquare_base? characterEncoding=utf‐8
    username: root
    password: 123456
    #指定服务的名称
  application:
    name: tensquare_base
